# Generated by Django 4.2.21 on 2026-03-08 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_family_alter_budget_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'permissions': [('can_set_budget', 'Может устанавливать лимиты бюджета')], 'verbose_name': 'Бюджет', 'verbose_name_plural': 'Бюджеты'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'permissions': [('can_manage_family', 'Может управлять составом семьи'), ('can_view_family_reports', 'Может просматривать общие отчеты семьи')], 'verbose_name': 'Семья', 'verbose_name_plural': 'Семьи'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at'], 'permissions': [('can_delete_any_transaction', 'Может удалять чужие транзакции'), ('can_import_export', 'Может импортировать и экспортировать данные')], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
