# Generated by Django 4.2.29 on 2026-03-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_create_default_groups'),
    ]

    operations = [
    ]
